# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  # config.vm.synced_folder "work", "/home/vagrant/work"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntn14"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # add apt-repository in this block
    sudo add-apt-repository -y ppa:webupd8team/java > /dev/null 2>&1

    # after newly added repo, this is required
    sudo apt-get -qq update

	# this is optional BTW,
    # sudo apt-get -y upgrade

    # installing java8 using apt-get install
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get -y -qq install oracle-java8-installer

	# install python - preferably miniconda
	curl -s https://repo.continuum.io/miniconda/Miniconda3-4.0.5-Linux-x86_64.sh -o miniconda.sh || exit 1
	bash miniconda.sh -b -f -p /opt/py3 > /dev/null 2>&1 || exit 1
	rm miniconda.sh || exit 1

  SHELL
end
